import {ThemeConfig} from 'antd';

export const configTheme: ThemeConfig = {
  token: {
    colorPrimary: 'var(--primary)',
    fontSize: 16,
    borderRadius: 16,
    colorSuccess: '#05fa4a',
  },
  components: {
    Tabs: {
      horizontalItemPaddingLG: '16px 24px',
      colorText: 'red',
      inkBarColor: 'var(--primary)',
      itemSelectedColor: 'var(--primary)',
      itemColor: '#3F485A',
      itemActiveColor: '#1B1B1B',
      colorBorderSecondary: '#EFEFEF',
      fontSize: 14,
    },
    Select: {
      paddingSM: 16,
      borderRadiusLG: 16,
      borderRadius: 16,
      paddingXS: 16,
      fontSizeSM: 14,
      activeBorderColor: 'var(--primary)',
      hoverBorderColor: 'rgb(0,0,0)',
      fontSizeIcon: 16,
      borderRadiusSM: 16,
      controlHeight: 52,
      colorBorder: 'rgb(63,72,90)',
      activeOutlineColor: 'rgba(68,34,239,0.27058823529411763)',
      optionSelectedBg: 'rgba(68,34,239,0.15)',
      borderRadiusXS: 4,
      fontFamily: 'Roboto',
      optionPadding: '16px 16px',
    },
    Input: {
      inputFontSize: 16,
      paddingBlock: 16,
      fontSize: 16,
      paddingXS: 16,
      borderRadius: 16,
      borderRadiusSM: 8,
      borderRadiusLG: 16,
      fontFamily: 'Roboto',
      fontSizeIcon: 16,
      paddingInline: 16,
      paddingInlineLG: 16,
      paddingInlineSM: 8,
      activeBorderColor: 'var(--primary)',
      hoverBorderColor: 'rgba(68,34,239,0.27058823529411763)',
    },
    Skeleton: {
      controlHeight: 82,
      padding: 12,
      marginSM: 24,
      controlHeightXS: 8,
      controlHeightSM: 32,
      controlHeightLG: 52,
      borderRadiusSM: 12,
    },
    Tag: {
      fontFamily: 'Roboto',
      fontSize: 16,
      fontSizeSM: 16,
      borderRadiusSM: 8,
      lineWidth: 1,
      paddingXXS: 8,
    },

    Typography: {
      fontSizeHeading1: 62,
      fontSizeHeading2: 48,
      fontSizeHeading3: 36,
      fontSizeHeading4: 24,
      titleMarginBottom: '0',
      titleMarginTop: '0',
      fontFamilyCode: "'Logos'",
      fontWeightStrong: 800,
    },
    // Checkbox: {
    //   colorWhite: 'rgb(39,44,0)',
    // },
    // DatePicker: {
    //   colorTextLightSolid: 'rgb(39,44,0)',
    // },
    // Radio: {
    //   dotSize: 12,
    //   radioSize: 24,
    //   buttonSolidCheckedColor: 'rgb(39,44,0)',
    //   buttonCheckedBg: 'rgb(39,44,0)',
    //   colorBorder: 'rgb(67,67,67)',
    //   dotColorDisabled: 'rgba(0,0,0,0.16)',
    // },
    // Select: {
    //   controlHeight: 48,
    //   controlHeightLG: 58,
    //   controlHeightSM: 38,
    //   colorBorder: 'rgb(67,67,67)',
    //   colorPrimary: 'rgb(241,255,11)',
    //   multipleItemBg: 'rgba(0,0,0,0.37)',
    //   colorTextPlaceholder: 'rgba(250,250,250,0.8)',
    //   optionSelectedBg: 'rgb(71,80,5)',
    // },
    // Slider: {
    //   handleColor: 'rgb(241,255,11)',
    //   dotBorderColor: 'rgb(241,255,11)',
    //   dotActiveBorderColor: 'rgb(241,255,11)',
    //   handleActiveOutlineColor: 'rgba(243,255,11,0.23)',
    //   trackBg: 'rgb(241,255,11)',
    // },
    // Switch: {
    //   handleBg: 'rgb(241,255,11)',
    //   handleSize: 24,
    //   trackHeight: 32,
    //   trackMinWidth: 48,
    //   trackPadding: 4,
    //   innerMinMarginSM: 6,
    //   handleSizeSM: 12,
    //   colorPrimary: 'rgb(0,0,0)',
    // },
  },
};
